### ISSUE TITLE
切换到横屏后，不能完全划出屏幕。

### ISSUE THREAD

**Issue by Leu-Z** [Yellow5A5/ClearScreenHelper#1]
自己之前自定义过类似的布局，右划划出屏幕，左滑划入。后来有横屏需求，发现之前右划的距离是根据竖屏屏宽定死的，切换到横屏后这个距离如果不变，右划只能滑动屏幕中间，并不能完全划出屏幕。

建议加入检测横竖屏动态改变滑动距离的功能。

**Comment by Yellow5A5** [comment]
抱歉，这么迟才看到回你的问题。
我写的这个工具View大小不是写死的，切换为横屏的时候View时会重建的，所以自然会重新根据比例去拿横屏对应的滑动距离，所以你说的这个问题是不会有的，已自测，是兼容横竖屏的。
