### ISSUE TITLE
为什么不直接用viewpager 呢 ？？

### ISSUE THREAD

**Issue by lgengsy** [Yellow5A5/ClearScreenHelper#2]

**Comment by Yellow5A5** [comment]
@lgengsy 
问题问的不够具体呀。。
是指直接包一层ViewPager，将所有要划屏清除的View塞进去实现么？
ViewPager被划出后还是覆盖在布局内其下层其他按钮就失效啦，所以不行。。。即使想要实现滑动清屏的效果也不会用ViewPager去处理的，试试你就知道了。

问题有点怪呀，感觉你没有站在这个场景去思考实现过程会遇到的问题。
