### ISSUE TITLE
为什么在布局里面放其他布局，点击事件会被屏蔽 能解决下吗

### ISSUE THREAD

**Issue by JsonNC** [Yellow5A5/ClearScreenHelper#3]
我在RelativeRootView里面放了一个正常的相对布局，里面的点击事件被屏蔽了  麻烦帮我看看 谢谢

**Comment by Yellow5A5** [comment]
@JsonNC
把你的布局文件贴出来我看一下～

或者参考下sample里的代码
https://github.com/Yellow5A5/ClearScreenHelper/blob/master/sample/src/main/res/layout/activity_sample_fir.xml

**Comment by Yellow5A5** [comment]
@JsonNC 
Hi～感谢你提出的问题，已修复，引用1.0.1版本即可。

**Comment by W-quan** [comment]
1.0.2版，滑动事件还是会冲突。  内部recycleview 左右滑动，事件应该是优先处理才对。

**Comment by Licarey** [comment]
@Yellow5A5 点击事件还是会被屏蔽掉

**Comment by Yellow5A5** [comment]
@Licarey 直接使用本工程测试没有你说的问题  另外这代码很久没改了  可以自己Debug看看 原理还是比较简单的 如果发现问题所在欢迎pr反馈 感谢
