### ISSUE TITLE
你好  还是我  我发现 我按住往右滑动不松手，然后往左滑，有的时候他会距离左边一段距离停下

### ISSUE THREAD

**Issue by JsonNC** [Yellow5A5/ClearScreenHelper#4]
按住往右滑动不松手，然后往左滑，有的时候他会距离左边一段距离停下

**Comment by Yellow5A5** [comment]
@JsonNC 
按你的方式进行操作测试但没有测出这样的问题～～
贴一下代码或者给下复现路径...这样的问题不应该呀

**Comment by hukejia** [comment]
同样的问题，快速右左，或者快速左右都会出现

**Comment by JsonNC** [comment]
@hukejia 我换了一种方式  你可以使用viewpager

**Comment by hukejia** [comment]
@JsonNC  viewpager对目前格局影响太大了，改起来不方便，如果实在不行就只有硬着头皮换了

**Comment by Yellow5A5** [comment]
@hukejia 再次自测了下，不是快速滑动的原因～发现是@JsonNC 的情况，在多点触碰时才会出现这样的停止～ Sorry～没有自测过这个Case～这周末前修复掉～抱歉了两位～😶

**Comment by Yellow5A5** [comment]
@hukejia 已修复此问题，并屏蔽了动画没结束时的二次点击，视觉上更友好些～1.0.2版本 🍻

**Comment by hukejia** [comment]
@Yellow5A5  还是会出现这个问题

**Comment by Yellow5A5** [comment]
@hukejia OK，知道你的Case问题了，类似的原因，今晚提一发解决～

**Comment by traywangjun** [comment]
作者还有维护么 这个情况好像还是会发生呀
